//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarEntities2 : DbContext
    {
        public CarEntities2()
            : base("name=CarEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<rental> rentals { get; set; }
        public virtual DbSet<@return> returns { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
