//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class rental
    {
        public int Id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<System.TimeSpan> pickup { get; set; }
        public Nullable<System.TimeSpan> dropoff { get; set; }
        public Nullable<System.TimeSpan> total_run { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> driver_id { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string status { get; set; }
    
        public virtual car car { get; set; }
        public virtual customer customer { get; set; }
        public virtual driver driver { get; set; }
    }
}
