//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @return
    {
        public int Id { get; set; }
        public Nullable<int> car_id { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public int customer_id { get; set; }
        public Nullable<decimal> penalty { get; set; }
    
        public virtual car car { get; set; }
        public virtual customer customer { get; set; }
    }
}
